- name: run solr and mysql docker containers on back vm
  docker_service:
    project_name: "testproject"
    definition:
      version: '2'
      services:
        db: 
        image:  nexushost.localdomain:8082/mysql:5.7
          environment:
               MYSQL_DATABASE: "{{databasename}}"
               MYSQL_PASSWORD: "{{userpassword}}"
               MYSQL_USER: "{{dbuser}}"
               MYSQL_ROOT_PASSWORD: "{{rootdbpassword}}"
               MYSQL_ROOT_HOST: "%"
          network_mode: "host"
          volumes:
            - "/datadrive/dump:/var/dump"
            - "/datadrive/datadb:/var/lib/mysql"
          ports:
            - "3306:3306"
          tty: true
        solr:
            build: 
                context: /home/faika/projetphp/backapp/docker/solr
            ports:
              - "8983:8983"
            volumes:
              - "/datadrive/solrcore/core1:/var/solr/data/core1"
            tty: true
