---
- hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml
  roles:
    - installations
    - mountdisk

- hosts: back
  become: yes
  vars_files:
    - group_vars/dev.yml
  roles:
    - deployback

- hosts: middle
  become: yes
  vars_files:
    - group_vars/dev.yml
  roles:
    - deploymiddle

- hosts: frontadmin
  become: yes
  vars_files:
    - group_vars/dev.yml
  roles:
    - deployfrontadmin  
