---
- hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml
  roles:
    - installations
      #    - mountdisk

      #- hosts: back
      #  become: yes
      #  vars_files:
      #    - group_vars/rec.yml
      #  roles:
      #    - deployback

      #- hosts: middle
      #  roles:
      #"    - deploymiddle

      #- hosts: frontadmin
      #  roles:
          #    - deployfrontadmin  
