---
- name: update system
  become: yes
  apt: update_cache=yes

- name: verifier dependances
  become: yes
  apt: name={{ item }}  state=present
  with_items:
    - apt-transport-https 
    - ca-certificates
    - curl
    - software-properties-common

- name: add official GPG key for docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  
- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present


- name: apt update
  become: yes
  apt: update_cache=yes

- name: installation docker
  become: yes
  apt: 
    name: docker-ce
    state: present

- name: installation docker compose
  become: yes
  get_url:
    url:  https://github.com/docker/compose/releases/download/1.17.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "+x"

- name: Installation ntp et snmp
  become: yes
  apt: name={{ item }}  state=present  update_cache=yes
  with_items:
    - ntp
    - snmp
    - snmpd
    - snmp-mibs-downloader

- name: remove localtime
  become: yes
  file: path=/etc/localtime state=absent

- name: copy ntp config file
  become: yes
  template: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp

- name: symlink localtime
  become: yes
  file:
    src: /usr/share/zoneinfo/Europe/Paris 
    dest: /etc/localtime
    state: link

- name: date system
  command: date
  register: date

- debug: msg="{{ date }}"
