---
- name: update system
  become: yes
  apt: update_cache=yes

- name: verifier dependances
  become: yes
  apt: name={{ item }}  state=present
  with_items:
    - apt-transport-https 
    - ca-certificates
    - curl
    - software-properties-common

- name: add official GPG key for docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  
- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present


- name: apt update
  become: yes
  apt: update_cache=yes

- name: installation docker
  become: yes
  apt: 
    name: docker-ce
    state: present

- name: installation docker compose
  become: yes
  get_url:
    url:  https://github.com/docker/compose/releases/download/1.17.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "+x"

- name: Installation ntp et snmp
  become: yes
  apt: name={{ item }}  state=present  update_cache=yes
  with_items:
    - ntp
    - snmp
    - snmpd
    - snmp-mibs-downloader

        #- name: creation sslcrf
        #    become: yes
        #    file:
        #      path: /etc/sslcarrefour
        #      state : present
        #      state: directory
        #      mode: 0777

        #- name : Creation des cles privees ssl
        #  openssl_privatekey : 
        #  path : /etc/sslcarrefour/{{item}}.key
        #  with_items :
        #    - "{{publicationbo_privatekeyname}}"
        #    - "{{frontadm_privatekeyname}}"

        #- name : generation des CSR
        #  openssl_csr:
        #  path: /etc/sslcarrefour/csr/{{item}}.csr
        #  privatekey_path: /etc/ssl/private/{{item}}.key
        #  country_name: FR
        #  organization_name: Carrefour France
        #  email_address: thomas_rufyiri@carrefour.com
        #  common_name: "{{item}}"
        #  with_items : 
        #    - "{{publicationbo_privatekeyname}}"
        #    - "{{frontadm_privatekeyname}}"

