- name: run recrute and enviedebouger container
  docker_service:
    project_name: "erecrute"
    definition:
      version: '2'
      services:
        php: 
          build: "/home/admindt/appmultihost/middleapp/docker/php7-fpm"
          args:
               APP_PROJECT_DIR_NAME: "{{APP_PROJECT_DIR_NAME}}"
          environment:
               SYMFONY__ENV: "{{SYMPHONY__ENV}}"
               SYMFONY__DB__HOST: "{{SYMPHONY__DB__HOST}}"
               SYMFONY__ERECRUTE__HOST: "{{SYMFONY__ERECRUTE__HOST}}"
               SYMFONY__ENVIEDEBOUGER__HOST: "{{SYMFONY__ENVIEDEBOUGER__HOST}}"
               SYMFONY__ADMIN__HOST: "{{SYMFONY__ADMIN__HOST}}"
               SYMFONY__SOLR__HOST: "{{SYMPHONY__SOLR__HOST}}"
          volumes:
            - "/datadrive/srcrecrute:/var/www/${APP_PROJECT_DIR_NAME}"
            - "/datadrive/logsrecrute/{{APP_PROJECT_DIR_NAME}}:/var/www/{{APP_PROJECT_DIR_NAME}}/app/logs"
          ports:
                  - "9000:9000"
                  - "25:25"
          
        apache:
            build: 
                context: "/home/admindt/appmultihost/middleapp/dokcer/apache"
            args:
                APP_PROJECT_DIR_NAME: "{{APP_PROJECT_DIR_NAME}}"
                APP_PROJECT_TYPE: "{{APP_PROJECT_TYPE}}"
            environment:
                APP_SERVER_NAME: "{{APP_SERVER_NAME}}"
                FRONT_CERT_NAME: "{FRONT_CERT_NAME}}"
                APP_PROJECT_DIR_NAME: "{{APP_PROJECT_DIR_NAME}}"
                APP_PHP_HOST: "{{APP__PHP__HOST}}"
                SYMFONY__ENV: "{{SYMPHONY__ENV}}"
                SYMFONY__DB__HOST: "{{SYMPHONY__DB__HOST}}"
                SYMFONY__ERECRUTE__HOST: "{{SYMFONY__ERECRUTE__HOST}}"
                SYMFONY__ENVIEDEBOUGER__HOST: "{{SYMFONY__ENVIEDEBOUGER__HOST}}"
                SYMFONY__ADMIN__HOST: "{{SYMFONY__ADMIN__HOST}}"
                SYMFONY__SOLR__HOST: "{{SYMPHONY__SOLR__HOST}}"
            ports:
                    - "443:443"
            volumes:
                    - "/datadrive/logsrecrute/apache/:/usr/local/apache2/logs"
                    - "/datadrive/srcrecrute:/var/www/{{APP_PROJECT_DIR_NAME}}"
                    - "/datadrive/logsrecrute/{{APP_PROJECT_DIR_NAME}}:/var/www/{{APP_PROJECT_DIR_NAME}}/app/logs"


