- name: run nginx container on front vm
  docker_service:
    project_name: "erecrute"
    definition:
      version: '2'
      services:
        nginx: 
            build: 
                context: /home/admindt/appmultihost/frontapp/docker/nginx
            environment:
                FRONT_CERT_NAME: "{{FRONT_CERT_NAME}}"
                APP_HOST: "{{APP_HOST}}"
            ports:
                    - "443:443"
                    - "80:80"
            volumes:
                    - "/datadrive/nginxlogs/:/var/log/nginx/"
            tty: true
